#in console:  docker-compose up

version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbit_new
    environment:
      RABBITMQ_DEFAULT_USER: agus #${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: agus #${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
