version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_USER=agus
      - POSTGRES_PASSWORD=agus
      - POSTGRES_DB=agus_database
    ports:
    - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.username=agus
      - sonar.jdbc.password=agus
      - sonar.jdbc.url=jdbc:postgresql://db:5432/agus_database
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

