version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_USER=agus
      - POSTGRES_PASSWORD=agus
      - POSTGRES_DB=agus_database
    ports:
    - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080